---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "09:00"
      timezone: UTC
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "09:00"
      timezone: UTC
    groups:
      docker:
        patterns:
          - "*"
    commit-message:
      prefix: "fix(docker)"
    labels:
      - dependencies

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "09:00"
      timezone: UTC
    groups:
      pip-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
